Update docs and reward tests
DoraFactory/dorafactory-node pull request #24
Opened 2022-05-19 02:01 UTC by VegeBun-csj

2022-05-19 02:22 UTC, 99Kies commented on pallets/dora-rewards/src/lib.rs
> +// GNU General Public License for more details.
Why `GPL`?

2022-05-19 15:31 UTC, tinydjp requested changes
在领取区块不能整除的情况下会导致最终领取到的奖励与应领取的不一致

2022-06-06 05:44 UTC, 99Kies commented
- [ ] add utility pallet. #23

2022-06-07 14:36 UTC, tinydjp approved these changes

2022-06-14 13:05 UTC, merged